name: 'Cerberus Review'
description: 'Run a single Cerberus code review perspective'
author: 'misty-step'

branding:
  icon: 'eye'
  color: 'red'

inputs:
  perspective:
    description: 'Review perspective (correctness, architecture, security, performance, maintainability, testing)'
    required: true
  github-token:
    description: 'GitHub token for PR comments'
    required: true
  api-key:
    description: 'OpenRouter API key (optional if CERBERUS_API_KEY or OPENROUTER_API_KEY env is set)'
    required: false
  kimi-api-key:
    description: 'Deprecated alias for api-key (OpenRouter API key)'
    required: false
  model:
    description: 'Model name (optional). If set, overrides per-reviewer config for this review (Cerberus will annotate when overridden).'
    default: ''
  fallback-models:
    description: 'Comma-separated fallback model names, tried in order when primary model fails with transient errors'
    default: 'openrouter/google/gemini-3-flash-preview,openrouter/z-ai/glm-5'
  max-steps:
    description: 'Max agentic steps per review'
    default: '25'
  timeout:
    description: 'Review timeout in seconds'
    default: '600'
  opencode-version:
    description: 'OpenCode CLI version to install'
    default: '1.1.49'
  post-comment:
    description: 'When to post reviewer comment to PR: never, non-pass (only on WARN/FAIL), or always'
    default: 'never'
  fail-on-skip:
    description: 'Exit with failure if review verdict is SKIP (timeout/API error)'
    default: 'false'
  context:
    description: 'Optional project context (maintainer-provided). Included in reviewer prompt. Do not include secrets.'
    default: ''

outputs:
  verdict:
    description: 'Review verdict (PASS, WARN, FAIL, SKIP)'
    value: ${{ steps.parse.outputs.verdict }}
  verdict-json:
    description: 'Path to verdict JSON file'
    value: ${{ steps.parse.outputs.verdict-json }}

runs:
  using: 'composite'
  steps:
    - name: Check fork safety
      shell: bash
      env:
        HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
        BASE_REPO: ${{ github.repository }}
      run: |
        if [[ -n "$HEAD_REPO" && "$HEAD_REPO" != "$BASE_REPO" ]]; then
          echo "::error::Cerberus does not run on fork PRs to protect secrets. Use pull_request trigger (not pull_request_target) and gate on same-repo PRs."
          exit 1
        fi

    - name: Validate perspective
      shell: bash
      env:
        PERSPECTIVE: ${{ inputs.perspective }}
      run: |
        VALID="correctness architecture security performance maintainability testing"
        if [[ ! " $VALID " =~ " $PERSPECTIVE " ]]; then
          echo "::error::Invalid perspective: $PERSPECTIVE. Must be one of: $VALID"
          exit 1
        fi

    - name: Resolve API key
      shell: bash
      env:
        CERBERUS_ROOT: ${{ github.action_path }}
        INPUT_API_KEY: ${{ inputs.api-key }}
        INPUT_KIMI_API_KEY: ${{ inputs.kimi-api-key }}
        CERBERUS_API_KEY: ${{ env.CERBERUS_API_KEY }}
        OPENROUTER_API_KEY: ${{ env.OPENROUTER_API_KEY }}
      run: |
        chmod +x "$CERBERUS_ROOT/scripts/validate-inputs.sh"
        "$CERBERUS_ROOT/scripts/validate-inputs.sh"

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python deps
      shell: bash
      run: pip install pyyaml --quiet

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '22'
        package-manager-cache: false

    - name: Install OpenCode CLI
      shell: bash
      env:
        OPENCODE_VERSION: ${{ inputs.opencode-version }}
      run: |
        if [[ ! "$OPENCODE_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "::error::Invalid opencode-version format: $OPENCODE_VERSION"
          exit 1
        fi
        npm i -g "opencode-ai@${OPENCODE_VERSION}"

    - name: Fetch PR context
      id: pr
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        if ! command -v gh >/dev/null 2>&1; then
          echo "::error::gh CLI not found on runner (required for PR context fetch)"
          exit 1
        fi
        if [[ -z "$PR_NUMBER" ]]; then
          echo "::error::This action must be triggered by a pull_request event"
          exit 1
        fi
        if ! gh pr diff "$PR_NUMBER" > /tmp/pr.diff; then
          echo "::error::Failed to fetch PR diff via gh pr diff."
          echo "Likely cause: missing workflow job permissions (pull-requests: read, contents: read) or incorrect github-token."
          echo ""
          echo "Fix (recommended):"
          echo "permissions:"
          echo "  contents: read"
          echo "  pull-requests: read"
          exit 1
        fi
        if ! gh pr view "$PR_NUMBER" --json title,author,headRefName,baseRefName,body > /tmp/pr-context.json; then
          echo "::error::Failed to fetch PR context via gh pr view."
          echo "Likely cause: missing workflow job permissions (pull-requests: read) or incorrect github-token."
          echo ""
          echo "Fix (recommended):"
          echo "permissions:"
          echo "  contents: read"
          echo "  pull-requests: read"
          exit 1
        fi
        echo "pr-number=$PR_NUMBER" >> "$GITHUB_OUTPUT"

    - name: Run review
      id: review
      shell: bash
      env:
        CERBERUS_ROOT: ${{ github.action_path }}
        PERSPECTIVE: ${{ inputs.perspective }}
        OPENROUTER_API_KEY: ${{ env.OPENROUTER_API_KEY }}
        OPENCODE_MODEL: ${{ inputs.model }}
        CERBERUS_CONTEXT: ${{ inputs.context }}
        CERBERUS_FALLBACK_MODELS: ${{ inputs.fallback-models }}
        OPENCODE_MAX_STEPS: ${{ inputs.max-steps }}
        REVIEW_TIMEOUT: ${{ inputs.timeout }}
        GH_DIFF_FILE: /tmp/pr.diff
        GH_PR_CONTEXT: /tmp/pr-context.json
      run: |
        chmod +x "$CERBERUS_ROOT/scripts/run-reviewer.sh"
        review_started_at=$(date +%s)
        set +e
        "$CERBERUS_ROOT/scripts/run-reviewer.sh" "$PERSPECTIVE"
        review_exit=$?
        review_finished_at=$(date +%s)
        runtime_seconds=$((review_finished_at - review_started_at))
        printf '%s\n' "$runtime_seconds" > "/tmp/${PERSPECTIVE}-runtime-seconds"
        exit "$review_exit"

    - name: Parse review output
      if: always()
      id: parse
      shell: bash
      env:
        CERBERUS_ROOT: ${{ github.action_path }}
        PERSPECTIVE: ${{ inputs.perspective }}
        PRIMARY_MODEL: ${{ inputs.model }}
        GH_DIFF_FILE: /tmp/pr.diff
      run: |
        # Resolve reviewer name written by run-reviewer.sh (e.g. APOLLO).
        # Falls back to uppercased perspective if the file is missing.
        REVIEWER_NAME_FILE="/tmp/${PERSPECTIVE}-reviewer-name"
        if [[ -s "$REVIEWER_NAME_FILE" ]]; then
          REVIEWER_NAME="$(cat "$REVIEWER_NAME_FILE")"
        else
          REVIEWER_NAME="${PERSPECTIVE^^}"
        fi
        export REVIEWER_NAME

        # Use scratchpad if available, else stdout
        PARSE_INPUT="/tmp/${PERSPECTIVE}-output.txt"
        if [[ -f "/tmp/${PERSPECTIVE}-parse-input" ]]; then
          PARSE_INPUT="$(cat "/tmp/${PERSPECTIVE}-parse-input")"
        fi
        python3 "$CERBERUS_ROOT/scripts/parse-review.py" "$PARSE_INPUT" > "/tmp/${PERSPECTIVE}-verdict.json"
        RUNTIME_FILE="/tmp/${PERSPECTIVE}-runtime-seconds"
        if [[ -f "$RUNTIME_FILE" ]]; then
          runtime_seconds="$(cat "$RUNTIME_FILE")"
          if [[ "$runtime_seconds" =~ ^[0-9]+$ ]]; then
            tmp_json="/tmp/${PERSPECTIVE}-verdict.runtime.json"
            jq --argjson runtime_seconds "$runtime_seconds" '.runtime_seconds = $runtime_seconds' "/tmp/${PERSPECTIVE}-verdict.json" > "$tmp_json"
            mv "$tmp_json" "/tmp/${PERSPECTIVE}-verdict.json"
          fi
        fi
        # Inject model metadata from run-reviewer.sh
        MODEL_USED_FILE="/tmp/${PERSPECTIVE}-model-used"
        if [[ -s "$MODEL_USED_FILE" ]]; then
          model_used="$(cat "$MODEL_USED_FILE")"
          PRIMARY_MODEL_FILE="/tmp/${PERSPECTIVE}-primary-model"
          if [[ -s "$PRIMARY_MODEL_FILE" ]]; then
            primary_model="$(cat "$PRIMARY_MODEL_FILE")"
          else
            primary_model="${PRIMARY_MODEL:-openrouter/moonshotai/kimi-k2.5}"
          fi
          CONFIGURED_MODEL_FILE="/tmp/${PERSPECTIVE}-configured-model"
          configured_model=""
          if [[ -s "$CONFIGURED_MODEL_FILE" ]]; then
            configured_model="$(cat "$CONFIGURED_MODEL_FILE")"
          fi
          fallback_used="false"
          if [[ "$model_used" != "$primary_model" ]]; then
            fallback_used="true"
          fi
          tmp_json="/tmp/${PERSPECTIVE}-verdict.model.json"
          jq --arg mu "$model_used" --arg pm "$primary_model" --arg cm "$configured_model" --argjson fb "$fallback_used" \
            '.model_used = $mu | .primary_model = $pm | .configured_model = $cm | .fallback_used = $fb' \
            "/tmp/${PERSPECTIVE}-verdict.json" > "$tmp_json"
          mv "$tmp_json" "/tmp/${PERSPECTIVE}-verdict.json"
        fi
        VERDICT=$(jq -r .verdict "/tmp/${PERSPECTIVE}-verdict.json")
        if [[ ! "$VERDICT" =~ ^(PASS|WARN|FAIL|SKIP)$ ]]; then
          echo "::error::Invalid verdict value from parser: $VERDICT"
          exit 1
        fi
        echo "verdict=$VERDICT" >> "$GITHUB_OUTPUT"
        echo "verdict-json=/tmp/${PERSPECTIVE}-verdict.json" >> "$GITHUB_OUTPUT"

    - name: Post PR comment
      if: steps.parse.outcome == 'success'
      shell: bash
      env:
        CERBERUS_ROOT: ${{ github.action_path }}
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ steps.pr.outputs.pr-number }}
        PERSPECTIVE: ${{ inputs.perspective }}
        GH_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        POST_COMMENT: ${{ inputs.post-comment }}
        VERDICT: ${{ steps.parse.outputs.verdict }}
      run: |
        # Determine if comment should be posted based on post-comment policy
        # Supports: never, non-pass, always (and legacy true/false for back-compat)
        should_post="false"
        case "$POST_COMMENT" in
          never|false|'')
            should_post="false"
            ;;
          always|true)
            should_post="true"
            ;;
          non-pass)
            if [[ "$VERDICT" == "WARN" || "$VERDICT" == "FAIL" || "$VERDICT" == "SKIP" ]]; then
              should_post="true"
            fi
            ;;
          *)
            echo "::warning::Unknown post-comment value '$POST_COMMENT', defaulting to never"
            should_post="false"
            ;;
        esac

        if [[ "$should_post" != "true" ]]; then
          echo "Skipping PR comment (post-comment=$POST_COMMENT, verdict=$VERDICT)"
          exit 0
        fi

        chmod +x "$CERBERUS_ROOT/scripts/post-comment.sh"
        "$CERBERUS_ROOT/scripts/post-comment.sh" "$PERSPECTIVE" "/tmp/${PERSPECTIVE}-verdict.json"

    - name: Upload verdict artifact
      if: steps.parse.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: cerberus-verdict-${{ inputs.perspective }}
        path: /tmp/${{ inputs.perspective }}-verdict.json
        retention-days: 1

    - name: Upload review document
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cerberus-review-${{ inputs.perspective }}
        path: /tmp/${{ inputs.perspective }}-review.md
        if-no-files-found: ignore
        retention-days: 3

    - name: Enforce verdict
      if: steps.parse.outcome == 'success'
      shell: bash
      env:
        VERDICT: ${{ steps.parse.outputs.verdict }}
        PERSPECTIVE: ${{ inputs.perspective }}
        FAIL_ON_SKIP: ${{ inputs.fail-on-skip }}
      run: |
        # Individual reviewers output their verdict but don't fail the job.
        # The Council Verdict job aggregates all reviews and makes the final decision.
        if [ "$VERDICT" = "FAIL" ]; then
          echo "::notice::${PERSPECTIVE} review verdict: FAIL (reported to council)"
        elif [ "$VERDICT" = "SKIP" ]; then
          if [ "$FAIL_ON_SKIP" = "true" ]; then
            echo "::error::${PERSPECTIVE} review verdict: SKIP (timeout/API error)"
            exit 1
          fi
          echo "::warning::${PERSPECTIVE} review verdict: SKIP (timeout/API error)"
        fi
