name: 'Cerberus Wave Gate'
description: 'Evaluate whether Cerberus should escalate to the next review wave'
author: 'misty-step'

inputs:
  verdict-dir:
    description: 'Directory containing wave verdict JSON artifacts'
    required: true
  wave:
    description: 'Current wave name (wave1, wave2, wave3)'
    required: true
  model-tier:
    description: 'Router-selected model tier (flash, standard, pro)'
    default: 'standard'

outputs:
  escalate:
    description: 'true when next wave should run, else false'
    value: ${{ steps.gate.outputs.escalate }}
  blocking:
    description: 'true when current wave had blocking conditions'
    value: ${{ steps.gate.outputs.blocking }}
  next-wave:
    description: 'Next wave name when escalation is true'
    value: ${{ steps.gate.outputs.next-wave }}
  reason:
    description: 'Gate reason code'
    value: ${{ steps.gate.outputs.reason }}
  telemetry-json:
    description: 'Path to wave gate telemetry JSON'
    value: ${{ steps.gate.outputs.telemetry-json }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python deps
      shell: bash
      run: pip install pyyaml --quiet

    - name: Evaluate wave gate
      id: gate
      shell: bash
      env:
        CERBERUS_ROOT: ${{ github.action_path }}/..
        INPUT_VERDICT_DIR: ${{ inputs.verdict-dir }}
        INPUT_WAVE: ${{ inputs.wave }}
        INPUT_MODEL_TIER: ${{ inputs.model-tier }}
      run: |
        telemetry_json="${RUNNER_TEMP}/cerberus-${INPUT_WAVE}-gate.json"
        gate_output="$(python3 "$CERBERUS_ROOT/scripts/evaluate-wave-gate.py" \
          --config "$CERBERUS_ROOT/defaults/config.yml" \
          --verdict-dir "$INPUT_VERDICT_DIR" \
          --wave "$INPUT_WAVE" \
          --tier "$INPUT_MODEL_TIER" \
          --output-json "$telemetry_json")"
        echo "$gate_output"

        escalate="$(printf '%s\n' "$gate_output" | awk -F= '$1=="escalate"{print $2}' | tail -n1)"
        blocking="$(printf '%s\n' "$gate_output" | awk -F= '$1=="blocking"{print $2}' | tail -n1)"
        next_wave="$(printf '%s\n' "$gate_output" | awk -F= '$1=="next_wave"{print $2}' | tail -n1)"
        reason="$(printf '%s\n' "$gate_output" | awk -F= '$1=="reason"{print $2}' | tail -n1)"

        echo "escalate=${escalate:-false}" >> "$GITHUB_OUTPUT"
        echo "blocking=${blocking:-false}" >> "$GITHUB_OUTPUT"
        echo "next-wave=${next_wave}" >> "$GITHUB_OUTPUT"
        echo "reason=${reason}" >> "$GITHUB_OUTPUT"
        echo "telemetry-json=${telemetry_json}" >> "$GITHUB_OUTPUT"
