name: 'Cerberus Matrix'
description: 'Output the current Cerberus reviewer matrix from defaults/config.yml'
author: 'misty-step'

branding:
  icon: 'list'
  color: 'blue'

inputs:
  panel:
    description: 'JSON array of perspective strings to filter the matrix (from router). Empty = all reviewers.'
    default: ''
  model-tier:
    description: 'Model complexity tier propagated from router output'
    default: 'standard'

outputs:
  matrix:
    description: 'JSON matrix of reviewers for use in strategy.matrix'
    value: ${{ steps.generate.outputs.matrix }}
  count:
    description: 'Number of reviewers in the matrix'
    value: ${{ steps.generate.outputs.count }}
  reviewers:
    description: 'Comma-separated list of reviewer names'
    value: ${{ steps.generate.outputs.reviewers }}

runs:
  using: 'composite'
  steps:
    - name: Generate matrix from config
      id: generate
      shell: bash
      env:
        CERBERUS_ROOT: ${{ github.action_path }}/..
        PANEL_FILTER: ${{ inputs.panel }}
        INPUT_MODEL_TIER: ${{ inputs.model-tier }}
      run: |
        config_file="${CERBERUS_ROOT}/defaults/config.yml"

        if [[ ! -f "$config_file" ]]; then
          echo "::error::Config file not found: $config_file"
          exit 1
        fi

        routing_enabled="$(python3 - <<'PY'
import yaml

with open("${config_file}", "r", encoding="utf-8") as f:
    cfg = yaml.safe_load(f) or {}

routing = cfg.get("routing", {}) or {}
enabled = routing.get("enabled", False)
print(str(bool(enabled)).lower())
PY
        )"

        if [[ "${PANEL_FILTER:-}" == "" || "${PANEL_FILTER:-}" == "[]" ]]; then
          if [[ "$routing_enabled" == "true" ]]; then
            echo "::warning::Routing is enabled in defaults/config.yml but no panel was passed to cerberus/matrix. All 8 reviewers will run. To enable reviewer selection, add the route step from templates/consumer-workflow-minimal.yml."
          fi
        fi

        pip install pyyaml --quiet

        MODEL_TIER="$INPUT_MODEL_TIER" python3 "${{ github.action_path }}/generate-matrix.py" "$config_file" > /dev/null

        if [[ -n "${PANEL_FILTER:-}" && "$PANEL_FILTER" != "[]" ]]; then
          python3 "${{ github.action_path }}/filter-panel.py" "$PANEL_FILTER"
        fi

        matrix_json=$(cat /tmp/matrix-output.json)
        count=$(cat /tmp/matrix-count.txt)
        names=$(cat /tmp/matrix-names.txt)

        echo "matrix=$matrix_json" >> "$GITHUB_OUTPUT"
        echo "count=$count" >> "$GITHUB_OUTPUT"
        echo "reviewers=$names" >> "$GITHUB_OUTPUT"

        echo "Generated matrix with $count reviewers: $names"
