name: 'Cerberus Council Verdict'
description: 'Aggregate Cerberus review verdicts into a council decision'
author: 'misty-step'

inputs:
  github-token:
    description: 'GitHub token for PR comments'
    required: true
  fail-on-verdict:
    description: 'Exit with failure if council verdict is FAIL'
    default: 'true'

outputs:
  verdict:
    description: 'Council verdict (PASS, WARN, FAIL)'
    value: ${{ steps.aggregate.outputs.verdict }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: .

    - name: Download verdict artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./verdicts/
        pattern: cerberus-verdict-*
        merge-multiple: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Check for override
      id: override
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
      run: |
        # REST issue comments use .user.login; GraphQL comments use .author.login.
        if ! OVERRIDE=$(gh api "repos/${REPO}/issues/${PR_NUMBER}/comments" --jq '[.[] | select(.body | startswith("/council override")) | {actor: .user.login, body: .body}] | last' 2>&1); then
          echo "::warning::Failed to fetch override comments: $OVERRIDE"
          OVERRIDE=""
        fi
        {
          echo "override<<CERBERUS_OVERRIDE_EOF"
          echo "$OVERRIDE"
          echo "CERBERUS_OVERRIDE_EOF"
        } >> "$GITHUB_OUTPUT"

    - name: Aggregate verdicts
      id: aggregate
      shell: bash
      env:
        CERBERUS_ROOT: ${{ github.action_path }}/..
        GH_OVERRIDE_COMMENT: ${{ steps.override.outputs.override }}
        GH_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        GH_PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        GH_OVERRIDE_POLICY: pr_author
      run: |
        python3 "$CERBERUS_ROOT/scripts/aggregate-verdict.py" ./verdicts/
        echo "verdict=$(jq -r .verdict /tmp/council-verdict.json)" >> "$GITHUB_OUTPUT"

    - name: Post council verdict
      if: always() && steps.aggregate.outcome == 'success'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
      run: |
        VERDICT=$(jq -r .verdict /tmp/council-verdict.json)
        SUMMARY=$(jq -r .summary /tmp/council-verdict.json)
        if [ "$VERDICT" = "null" ] || [ -z "$VERDICT" ]; then
          echo "::error::Council verdict JSON is malformed"
          exit 1
        fi
        EMOJI="✅"
        if [ "$VERDICT" = "FAIL" ]; then EMOJI="❌"; fi
        if [ "$VERDICT" = "WARN" ]; then EMOJI="⚠️"; fi
        if [ "$VERDICT" = "SKIP" ]; then EMOJI="⏭️"; fi
        MARKER="<!-- cerberus:council -->"

        {
          echo "$MARKER"
          echo "## ${EMOJI} Council Verdict: ${VERDICT}"
          echo ""
          echo "$SUMMARY"
          echo ""
          echo "---"
          echo "*Cerberus Council*"
        } > /tmp/council-comment.md

        print_permissions_help() {
          {
            echo "::error::Unable to post council PR comment: token lacks pull request write permission."
            echo "Add this to your workflow:"
            echo "permissions:"
            echo "  contents: read"
            echo "  pull-requests: write"
          } >&2
        }

        EXISTING=$(gh api "repos/${REPO}/issues/${PR_NUMBER}/comments" --jq '.[] | select(.body | contains("cerberus:council")) | .id' 2>/tmp/cerberus-council.err | head -1) || true
        if [ -n "$EXISTING" ]; then
          # Pass body via gh's @file reader to avoid shell interpolation of comment content.
          if ! gh api "repos/${REPO}/issues/comments/${EXISTING}" -X PATCH -F body=@/tmp/council-comment.md >/tmp/cerberus-council.out 2>/tmp/cerberus-council.err; then
            cat /tmp/cerberus-council.err >&2
            if grep -qiE "403|resource not accessible by integration|insufficient" /tmp/cerberus-council.err; then
              print_permissions_help
            fi
            exit 1
          fi
        else
          if ! gh pr comment "$PR_NUMBER" --body-file /tmp/council-comment.md >/tmp/cerberus-council.out 2>/tmp/cerberus-council.err; then
            cat /tmp/cerberus-council.err >&2
            if grep -qiE "403|resource not accessible by integration|insufficient" /tmp/cerberus-council.err; then
              print_permissions_help
            fi
            exit 1
          fi
        fi

    - name: Check verdict
      if: always() && steps.aggregate.outcome == 'success' && inputs.fail-on-verdict == 'true'
      shell: bash
      run: |
        VERDICT=$(jq -r .verdict /tmp/council-verdict.json)
        if [ "$VERDICT" = "FAIL" ]; then
          echo "::error::Council Verdict: FAIL"
          exit 1
        fi
        if [ "$VERDICT" = "SKIP" ]; then
          echo "::notice::Council Verdict: SKIP (all reviews skipped due to API errors)"
          exit 0
        fi
