name: 'Cerberus Verdict'
description: 'Aggregate Cerberus review verdicts into a verdict decision'
author: 'misty-step'

inputs:
  github-token:
    description: 'GitHub token for PR comments'
    required: true
  fail-on-verdict:
    description: 'Exit with failure if verdict is FAIL'
    default: 'true'
  fail-on-skip:
    description: 'Exit with failure if verdict is SKIP (all reviews skipped)'
    default: 'false'
  parse-failure-policy:
    description: 'How to treat reviewer parse failures in verdict aggregation: fail (count as FAIL), warn (reclassify as SKIP with warning, default), skip (reclassify as SKIP silently)'
    default: 'warn'

outputs:
  verdict:
    description: 'Cerberus verdict (PASS, WARN, FAIL, SKIP)'
    value: ${{ steps.aggregate.outputs.verdict }}

runs:
  using: 'composite'
  steps:
    - name: Create isolated temp directory
      shell: bash
      run: |
        cerberus_tmp="$(mktemp -d -t cerberus.XXXXXX)"
        chmod 0700 "$cerberus_tmp"
        echo "CERBERUS_TMP=${cerberus_tmp}" >> "$GITHUB_ENV"

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download verdict artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./verdicts/
        pattern: cerberus-verdict-*
        merge-multiple: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Read reviewer policies from config
      id: policies
      shell: bash
      env:
        CERBERUS_ROOT: ${{ github.action_path }}/..
      run: |
        CONFIG="$CERBERUS_ROOT/defaults/config.yml"
        python3 - "$CONFIG" <<'PYEOF'
        import json, os, re, sys
        config_path = sys.argv[1]
        with open(config_path) as fh:
            raw = fh.read()
        # Strip comment-only lines to prevent matching commented-out entries.
        text = "\n".join(
            line for line in raw.splitlines()
            if not line.lstrip().startswith("#")
        )
        # Extract global override actor policy.
        m = re.search(r'^\s*override:\s*\n(?:.*\n)*?^\s+actor:\s*(\S+)', text, re.MULTILINE)
        global_policy = m.group(1).strip("\"'") if m else "pr_author"
        # Extract per-reviewer override policies from reviewers list.
        policies = {}
        for block in re.finditer(
            r'^\s*-\s+name:\s*(\S+).*?(?=^\s*-\s+name:|\Z)', text, re.DOTALL | re.MULTILINE
        ):
            name = block.group(1).strip("\"'")
            om = re.search(r'^\s*override:\s*(\S+)', block.group(0), re.MULTILINE)
            if om:
                policies[name] = om.group(1).strip("\"'")
            else:
                policies[name] = global_policy
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"global_policy={global_policy}\n")
            f.write(f"reviewer_policies={json.dumps(policies)}\n")
        PYEOF

    - name: Check for override
      id: override
      shell: bash
      env:
        CERBERUS_ROOT: ${{ github.action_path }}/..
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
      run: |
        python3 "$CERBERUS_ROOT/scripts/collect-overrides.py" \
          --repo "$REPO" \
          --pr "$PR_NUMBER" \
          --github-output "$GITHUB_OUTPUT"

    - name: Aggregate verdicts
      id: aggregate
      shell: bash
      env:
        CERBERUS_ROOT: ${{ github.action_path }}/..
        GH_OVERRIDE_COMMENTS: ${{ steps.override.outputs.overrides }}
        GH_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        GH_PR_NUMBER: ${{ github.event.pull_request.number }}
        GH_PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        GH_OVERRIDE_POLICY: ${{ steps.policies.outputs.global_policy }}
        GH_REVIEWER_POLICIES: ${{ steps.policies.outputs.reviewer_policies }}
        GH_OVERRIDE_ACTOR_PERMISSIONS: ${{ steps.override.outputs.actor_permissions }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PARSE_FAILURE_POLICY: ${{ inputs.parse-failure-policy }}
      run: |
        python3 "$CERBERUS_ROOT/scripts/aggregate-verdict.py" ./verdicts/
        VERDICT=$(jq -r .verdict "${CERBERUS_TMP}/verdict.json" 2>/dev/null)
        if [ "$VERDICT" = "null" ] || [ -z "$VERDICT" ]; then
          echo "::warning::aggregate-verdict.py did not write a valid .verdict; defaulting to SKIP"
          echo "verdict.json contents:" >&2
          cat "${CERBERUS_TMP}/verdict.json" 2>/dev/null || echo "(file missing)" >&2
          VERDICT="SKIP"
        fi
        echo "verdict=$VERDICT" >> "$GITHUB_OUTPUT"

    - name: Post verdict
      if: always() && steps.aggregate.outcome == 'success'
      shell: bash
      env:
        CERBERUS_ROOT: ${{ github.action_path }}/..
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
        GH_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        GH_OVERRIDE_POLICY: ${{ steps.policies.outputs.global_policy }}
        PR_CHANGED_FILES: ${{ github.event.pull_request.changed_files }}
        PR_ADDITIONS: ${{ github.event.pull_request.additions }}
        PR_DELETIONS: ${{ github.event.pull_request.deletions }}
        FAIL_ON_VERDICT: ${{ inputs.fail-on-verdict }}
        CERBERUS_VERSION: ${{ github.action_ref || 'dev' }}
      run: |
        VERDICT="${{ steps.aggregate.outputs.verdict }}"
        if [ "$VERDICT" = "null" ] || [ -z "$VERDICT" ]; then
          echo "::error::Cerberus verdict output is empty; was the aggregate step skipped or failed?"
          exit 1
        fi
        python3 "$CERBERUS_ROOT/scripts/render-verdict-comment.py" \
          --verdict-json "${CERBERUS_TMP}/verdict.json" \
          --output "${CERBERUS_TMP}/verdict-comment.md"

        python3 "$CERBERUS_ROOT/scripts/lib/github.py" \
          --repo "$REPO" \
          --pr "$PR_NUMBER" \
          --marker "<!-- cerberus:verdict -->" \
          --body-file "${CERBERUS_TMP}/verdict-comment.md"

    - name: Post inline review comments
      if: always() && steps.aggregate.outcome == 'success'
      shell: bash
      env:
        CERBERUS_ROOT: ${{ github.action_path }}/..
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
        GH_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        python3 "$CERBERUS_ROOT/scripts/post-verdict-review.py" \
          --repo "$REPO" \
          --pr "$PR_NUMBER" \
          --head-sha "$GH_HEAD_SHA" \
          --verdict-json "${CERBERUS_TMP}/verdict.json" \
          --body-file "${CERBERUS_TMP}/verdict-comment.md"

    - name: Upload quality report artifact
      if: always() && steps.aggregate.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: cerberus-quality-report
        path: ${{ env.CERBERUS_TMP }}/quality-report.json
        retention-days: 30

    - name: Check verdict
      if: always() && steps.aggregate.outcome == 'success' && (inputs.fail-on-verdict == 'true' || inputs.fail-on-skip == 'true')
      shell: bash
      env:
        FAIL_ON_VERDICT: ${{ inputs.fail-on-verdict }}
        FAIL_ON_SKIP: ${{ inputs.fail-on-skip }}
      run: |
        VERDICT="${{ steps.aggregate.outputs.verdict }}"
        if [ "$VERDICT" = "FAIL" ] && [ "$FAIL_ON_VERDICT" = "true" ]; then
          echo "::error::Cerberus Verdict: FAIL"
          exit 1
        fi
        if [ "$VERDICT" = "SKIP" ]; then
          if [ "$FAIL_ON_SKIP" = "true" ]; then
            echo "::error::Cerberus Verdict: SKIP (all reviews skipped due to timeout/API errors)"
            exit 1
          fi
          echo "::notice::Cerberus Verdict: SKIP (all reviews skipped due to timeout/API errors)"
        fi

    - name: Clean up temp directory
      if: always()
      shell: bash
      run: |
        if [[ -n "${CERBERUS_TMP:-}" && -d "${CERBERUS_TMP}" ]]; then
          # Best-effort cleanup only: temp deletion failures should not fail verdict jobs.
          chmod -R u+rwX "${CERBERUS_TMP}" 2>/dev/null || true
          rm -rf "${CERBERUS_TMP}" 2>/dev/null || true
          if [[ -d "${CERBERUS_TMP}" ]]; then
            echo "::warning::Failed to fully clean temporary directory: ${CERBERUS_TMP}"
          fi
        fi
