name: 'Cerberus Council Verdict'
description: 'Aggregate Cerberus review verdicts into a council decision'
author: 'misty-step'

inputs:
  github-token:
    description: 'GitHub token for PR comments'
    required: true
  fail-on-verdict:
    description: 'Exit with failure if council verdict is FAIL'
    default: 'true'
  fail-on-skip:
    description: 'Exit with failure if council verdict is SKIP (all reviews skipped)'
    default: 'false'

outputs:
  verdict:
    description: 'Council verdict (PASS, WARN, FAIL, SKIP)'
    value: ${{ steps.aggregate.outputs.verdict }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download verdict artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./verdicts/
        pattern: cerberus-verdict-*
        merge-multiple: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Read reviewer policies from config
      id: policies
      shell: bash
      env:
        CERBERUS_ROOT: ${{ github.action_path }}/..
      run: |
        CONFIG="$CERBERUS_ROOT/defaults/config.yml"
        python3 - "$CONFIG" <<'PYEOF'
        import json, os, re, sys
        config_path = sys.argv[1]
        with open(config_path) as fh:
            raw = fh.read()
        # Strip comment-only lines to prevent matching commented-out entries.
        text = "\n".join(
            line for line in raw.splitlines()
            if not line.lstrip().startswith("#")
        )
        # Extract global override actor policy.
        m = re.search(r'^\s*override:\s*\n(?:.*\n)*?^\s+actor:\s*(\S+)', text, re.MULTILINE)
        global_policy = m.group(1).strip("\"'") if m else "pr_author"
        # Extract per-reviewer override policies from reviewers list.
        policies = {}
        for block in re.finditer(
            r'^\s*-\s+name:\s*(\S+).*?(?=^\s*-\s+name:|\Z)', text, re.DOTALL | re.MULTILINE
        ):
            name = block.group(1).strip("\"'")
            om = re.search(r'^\s*override:\s*(\S+)', block.group(0), re.MULTILINE)
            if om:
                policies[name] = om.group(1).strip("\"'")
            else:
                policies[name] = global_policy
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"global_policy={global_policy}\n")
            f.write(f"reviewer_policies={json.dumps(policies)}\n")
        PYEOF

    - name: Check for override
      id: override
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
      run: |
        # Collect ALL override comments chronologically (not just the last one).
        # Python's select_override() iterates in order, picking the first authorized.
        if ! OVERRIDES=$(gh api "repos/${REPO}/issues/${PR_NUMBER}/comments" --jq '[.[] | select(.body | startswith("/council override")) | {actor: .user.login, body: .body}]' 2>&1); then
          echo "::warning::Failed to fetch override comments: $OVERRIDES"
          OVERRIDES="[]"
        fi
        {
          echo "overrides<<CERBERUS_OVERRIDE_EOF"
          echo "$OVERRIDES"
          echo "CERBERUS_OVERRIDE_EOF"
        } >> "$GITHUB_OUTPUT"

        # Resolve repo permissions for all unique override actors.
        ACTOR_PERMISSIONS="{}"
        if [ "$OVERRIDES" != "[]" ] && [ "$OVERRIDES" != "null" ] && [ -n "$OVERRIDES" ]; then
          # Decode and run Python script (base64 to avoid YAML parsing issues)
          ACTOR_PERMISSIONS=$(python3 -c "$(echo 'aW1wb3J0IGpzb24sIHN5cywgc3VicHJvY2Vzcwpjb21tZW50cyA9IGpzb24ubG9hZHMoc3lzLnN0ZGluLnJlYWQoKSkKYWN0b3JzID0gc29ydGVkKHNldChjLmdldCgiYWN0b3IiLCAiIikgZm9yIGMgaW4gY29tbWVudHMgaWYgYy5nZXQoImFjdG9yIikpKQpwZXJtcyA9IHt9CnJlcG8gPSBzeXMuYXJndlsxXQpmb3IgYWN0b3IgaW4gYWN0b3JzOgogICAgdHJ5OgogICAgICAgIHJlc3VsdCA9IHN1YnByb2Nlc3MucnVuKAogICAgICAgICAgICBbImdoIiwgImFwaSIsIGYicmVwb3Mve3JlcG99L2NvbGxhYm9yYXRvcnMve2FjdG9yfS9wZXJtaXNzaW9uIiwgIi0tanEiLCAiLnBlcm1pc3Npb24iXSwKICAgICAgICAgICAgY2FwdHVyZV9vdXRwdXQ9VHJ1ZSwgdGV4dD1UcnVlLCB0aW1lb3V0PTEwLAogICAgICAgICkKICAgICAgICBwZXJtc1thY3Rvcl0gPSByZXN1bHQuc3Rkb3V0LnN0cmlwKCkgaWYgcmVzdWx0LnJldHVybmNvZGUgPT0gMCBlbHNlICIiCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHBlcm1zW2FjdG9yXSA9ICIiCnByaW50KGpzb24uZHVtcHMocGVybXMpKQo=' | base64 -d)" "$REPO" <<< "$OVERRIDES" 2>/dev/null || echo "{}")
        fi
        echo "actor_permissions=$ACTOR_PERMISSIONS" >> "$GITHUB_OUTPUT"

    - name: Aggregate verdicts
      id: aggregate
      shell: bash
      env:
        CERBERUS_ROOT: ${{ github.action_path }}/..
        GH_OVERRIDE_COMMENTS: ${{ steps.override.outputs.overrides }}
        GH_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        GH_PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        GH_OVERRIDE_POLICY: ${{ steps.policies.outputs.global_policy }}
        GH_REVIEWER_POLICIES: ${{ steps.policies.outputs.reviewer_policies }}
        GH_OVERRIDE_ACTOR_PERMISSIONS: ${{ steps.override.outputs.actor_permissions }}
      run: |
        python3 "$CERBERUS_ROOT/scripts/aggregate-verdict.py" ./verdicts/
        echo "verdict=$(jq -r .verdict /tmp/council-verdict.json)" >> "$GITHUB_OUTPUT"

    - name: Post council verdict
      if: always() && steps.aggregate.outcome == 'success'
      shell: bash
      env:
        CERBERUS_ROOT: ${{ github.action_path }}/..
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
        GH_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        GH_OVERRIDE_POLICY: ${{ steps.policies.outputs.global_policy }}
        PR_CHANGED_FILES: ${{ github.event.pull_request.changed_files }}
        PR_ADDITIONS: ${{ github.event.pull_request.additions }}
        PR_DELETIONS: ${{ github.event.pull_request.deletions }}
        FAIL_ON_VERDICT: ${{ inputs.fail-on-verdict }}
        CERBERUS_VERSION: ${{ github.action_ref || 'dev' }}
      run: |
        VERDICT=$(jq -r .verdict /tmp/council-verdict.json)
        if [ "$VERDICT" = "null" ] || [ -z "$VERDICT" ]; then
          echo "::error::Council verdict JSON is malformed"
          exit 1
        fi
        python3 "$CERBERUS_ROOT/scripts/render-council-comment.py" \
          --council-json /tmp/council-verdict.json \
          --output /tmp/council-comment.md

        print_permissions_help() {
          {
            echo "::error::Unable to post council PR comment: token lacks pull request write permission."
            echo "Add this to your workflow:"
            echo "permissions:"
            echo "  contents: read"
            echo "  pull-requests: write"
          } >&2
        }

        EXISTING=$(gh api "repos/${REPO}/issues/${PR_NUMBER}/comments" --jq '.[] | select(.body | contains("cerberus:council")) | .id' 2>/tmp/cerberus-council.err | head -1) || true
        if [ -n "$EXISTING" ]; then
          # Pass body via gh's @file reader to avoid shell interpolation of comment content.
          if ! gh api "repos/${REPO}/issues/comments/${EXISTING}" -X PATCH -F body=@/tmp/council-comment.md >/tmp/cerberus-council.out 2>/tmp/cerberus-council.err; then
            cat /tmp/cerberus-council.err >&2
            if grep -qiE "403|resource not accessible by integration|insufficient" /tmp/cerberus-council.err; then
              print_permissions_help
            fi
            exit 1
          fi
        else
          if ! gh pr comment "$PR_NUMBER" --body-file /tmp/council-comment.md >/tmp/cerberus-council.out 2>/tmp/cerberus-council.err; then
            cat /tmp/cerberus-council.err >&2
            if grep -qiE "403|resource not accessible by integration|insufficient" /tmp/cerberus-council.err; then
              print_permissions_help
            fi
            exit 1
          fi
        fi

    - name: Check verdict
      if: always() && steps.aggregate.outcome == 'success' && (inputs.fail-on-verdict == 'true' || inputs.fail-on-skip == 'true')
      shell: bash
      env:
        FAIL_ON_VERDICT: ${{ inputs.fail-on-verdict }}
        FAIL_ON_SKIP: ${{ inputs.fail-on-skip }}
      run: |
        VERDICT=$(jq -r .verdict /tmp/council-verdict.json)
        if [ "$VERDICT" = "FAIL" ] && [ "$FAIL_ON_VERDICT" = "true" ]; then
          echo "::error::Council Verdict: FAIL"
          exit 1
        fi
        if [ "$VERDICT" = "SKIP" ]; then
          if [ "$FAIL_ON_SKIP" = "true" ]; then
            echo "::error::Council Verdict: SKIP (all reviews skipped due to timeout/API errors)"
            exit 1
          fi
          echo "::notice::Council Verdict: SKIP (all reviews skipped due to timeout/API errors)"
        fi
