# Cerberus AI Code Review — Decomposed Pipeline (Power User)
# https://github.com/misty-step/cerberus
#
# ⚠️ ADVANCED: This template exposes every job for direct customization.
# For most users, the reusable workflow is simpler (~13 lines):
#
#   See templates/consumer-workflow-reusable.yml
#
# Use this template when you need full control: custom job conditions,
# extra steps between stages, or per-job runner customization.
#
name: Cerberus

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, converted_to_draft]

concurrency:
  group: cerberus-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  preflight:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    outputs:
      should_run: ${{ steps.preflight.outputs.should_run }}
      skip_reason: ${{ steps.preflight.outputs.skip_reason }}
    steps:
      - uses: misty-step/cerberus/preflight@v2
        id: preflight
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.OPENROUTER_API_KEY }}

  # Preflight: validate workflow structure (permissions, required inputs, etc)
  validate:
    needs: preflight
    if: needs.preflight.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: misty-step/cerberus/validate@v2

  # Route: select the most relevant reviewers for this PR
  route:
    needs: [validate, preflight]
    if: needs.preflight.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      panel: ${{ steps.router.outputs.panel }}
      model-tier: ${{ steps.router.outputs.model-tier }}
    steps:
      - uses: actions/checkout@v4
      - name: Fetch PR diff
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr diff ${{ github.event.pull_request.number }} > /tmp/pr.diff
      - uses: misty-step/cerberus/router@v2
        id: router
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.OPENROUTER_API_KEY }}
          diff-file: /tmp/pr.diff
          # routing: 'disabled'         # uncomment to skip LLM routing and use all reviewers
          # reviewers: 'trace,guard'    # uncomment to force specific reviewers (bypasses routing)

  # Generate the reviewer matrix, filtered by the router panel
  matrix:
    needs: route
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
      count: ${{ steps.generate.outputs.count }}
    steps:
      - id: generate
        uses: misty-step/cerberus/matrix@v2
        with:
          panel: ${{ needs.route.outputs.panel }}
          model-tier: ${{ needs.route.outputs.model-tier }}

  # Run reviews in parallel using the routed matrix
  review:
    needs: [matrix, preflight]
    if: needs.preflight.outputs.should_run == 'true'
    permissions:
      contents: read
      pull-requests: read
    name: "${{ matrix.reviewer_label || matrix.reviewer }}"
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: misty-step/cerberus@v2
        with:
          perspective: ${{ matrix.perspective }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.OPENROUTER_API_KEY }}
          comment-policy: 'never'
          timeout: '600'
          model-tier: ${{ matrix.model_tier }}
          # Optional: project/domain context to calibrate reviewer severity. Do not include secrets.
          # context: |
          #   Moneta is a single-user personal finance and tax tool.
          #   Data volumes are bounded: ~100-500 transactions per user per year.
          # Optional (not recommended): force one model for all reviewers (pins models; Cerberus will warn)
          # model: 'openrouter/moonshotai/kimi-k2.5'
          # fallback-models: 'openrouter/google/gemini-3-flash-preview,openrouter/z-ai/glm-5'
          # fail-on-skip: 'true' # optional: fail reviewer job if it SKIPs (timeout/API error)

  # Aggregate all review results into a single verdict comment
  verdict:
    name: "Verdict"
    needs: [review, preflight]
    if: always() && needs.review.result != 'skipped' && needs.preflight.outputs.should_run == 'true'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: misty-step/cerberus/verdict@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # fail-on-skip: 'true' # optional: fail if Cerberus verdict is SKIP (no review happened)
