# Cerberus AI Code Review Council
# https://github.com/misty-step/cerberus
# Fork PR security: repository secrets are unavailable to forks.
# Keep review job gated to same-repo PRs to avoid secret access attempts.
name: Cerberus Council

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: cerberus-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  review:
    if: github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: read
      pull-requests: read
    name: "${{ matrix.reviewer }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { reviewer: APOLLO, perspective: correctness }
          - { reviewer: ATHENA, perspective: architecture }
          - { reviewer: SENTINEL, perspective: security }
          - { reviewer: VULCAN, perspective: performance }
          - { reviewer: ARTEMIS, perspective: maintainability }
          - { reviewer: CASSANDRA, perspective: testing }
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: misty-step/cerberus@v2
        with:
          perspective: ${{ matrix.perspective }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.OPENROUTER_API_KEY }}
          post-comment: 'false'
          timeout: '600'
          # fallback-models: 'openrouter/deepseek/deepseek-v3.2,openrouter/google/gemini-3-flash-preview' # default fallback chain
          # fail-on-skip: 'true' # optional: fail reviewer job if it SKIPs (timeout/API error)

  # --- Advanced: per-reviewer model diversity ---
  # Assign different models to each reviewer for diverse analysis.
  # Uncomment and replace the review job above to use this configuration.
  #
  # review:
  #   if: github.event.pull_request.head.repo.full_name == github.repository
  #   permissions:
  #     contents: read
  #     pull-requests: read
  #   name: "${{ matrix.reviewer }}"
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       include:
  #         - { reviewer: APOLLO,    perspective: correctness,      model: 'openrouter/moonshotai/kimi-k2.5' }
  #         - { reviewer: ATHENA,    perspective: architecture,     model: 'openrouter/z-ai/glm-5' }
  #         - { reviewer: SENTINEL,  perspective: security,         model: 'openrouter/deepseek/deepseek-v3.2' }
  #         - { reviewer: VULCAN,    perspective: performance,      model: 'openrouter/google/gemini-3-flash-preview' }
  #         - { reviewer: ARTEMIS,   perspective: maintainability,  model: 'openrouter/minimax/minimax-m2.1' }
  #         - { reviewer: CASSANDRA, perspective: testing,          model: 'openrouter/qwen/qwen3-coder-next' }
  #     fail-fast: false
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: misty-step/cerberus@v2
  #       with:
  #         perspective: ${{ matrix.perspective }}
  #         model: ${{ matrix.model }}
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         api-key: ${{ secrets.OPENROUTER_API_KEY }}
  #         post-comment: 'false'
  #         timeout: '600'

  verdict:
    name: "Council Verdict"
    needs: review
    if: always()
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: misty-step/cerberus/verdict@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # fail-on-skip: 'true' # optional: fail if council verdict is SKIP (no review happened)
