# Workflow Lint (Cerberus)
#
# Catches the GitHub "workflow file issue" class early by validating YAML + common
# Cerberus misconfigs from a separate workflow.
#
# Recommended: keep this even if Cerberus is disabled on fork PRs.
name: Cerberus Workflow Lint

on:
  push:
    paths:
      - .github/workflows/*.yml
      - .github/workflows/*.yaml
  pull_request:
    paths:
      - .github/workflows/*.yml
      - .github/workflows/*.yaml

permissions:
  contents: read

jobs:
  cerberus-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: misty-step/cerberus/validate@master
        with:
          workflow: .github/workflows/cerberus.yml
